host: 0.0.0.0
port: 8182
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphs: { graph: conf/tinkergraph-empty.properties }
scriptEngines:
  {
    gremlin-groovy:
      {
        plugins:
          {
            org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin:
              {},
            org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin:
              {},
            org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin:
              { files: [scripts/empty-sample.groovy] },
          },
      },
  }
serializers:
  - {
      className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1,
      config: { serializeResultToString: true },
    }
  - {
      className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0,
    }
  - {
      className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV2d0,
    }
  - {
      className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0,
    }
metrics: { consoleReporter: { enabled: true, interval: 180000 } }
